//! Primitive #15 — Provenance-Aware Context Assembly.
//!
//! Context quality depends on trust as much as relevance.
//! Every fragment carries metadata: source, trust, freshness, type.

use serde::{Deserialize, Serialize};

/// Where a context fragment came from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContextSource {
    /// User explicitly stated this.
    UserStated,
    /// Model inferred this from conversation.
    ModelInferred,
    /// Retrieved from persistent memory.
    MemoryRetrieval { memory_id: String },
    /// Loaded from project file (CLAUDE.md, etc.).
    ProjectFile { path: String },
    /// Retrieved from web search/fetch.
    WebRetrieval { url: String },
    /// Generated by compaction/summarization.
    Compaction,
    /// From MCP tool discovery.
    McpDiscovery { server: String },
}

/// Whether a fragment is instructive or evidential.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContextType {
    /// System instructions — treated as directives.
    Instruction,
    /// Evidence/data — treated as information.
    Evidence,
    /// Mixed or unknown.
    Mixed,
}

/// A context fragment with full provenance.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextFragment {
    pub content: String,
    pub source: ContextSource,
    pub context_type: ContextType,
    pub trust_score: f32,
    pub token_estimate: u32,
    pub created_at: String,
    pub last_validated: Option<String>,
    pub is_contradicted: bool,
}

/// Assemble context from multiple fragments with budget awareness.
pub struct ContextAssembler {
    fragments: Vec<ContextFragment>,
    token_budget: u32,
}

impl ContextAssembler {
    pub fn new(token_budget: u32) -> Self {
        Self {
            fragments: Vec::new(),
            token_budget,
        }
    }

    /// Add a fragment to the assembly pool.
    pub fn add(&mut self, fragment: ContextFragment) {
        self.fragments.push(fragment);
    }

    /// Assemble context within token budget, prioritizing by trust and relevance.
    pub fn assemble(&self) -> AssembledContext {
        let mut sorted: Vec<&ContextFragment> = self.fragments.iter()
            .filter(|f| !f.is_contradicted)
            .collect();

        // Sort by trust score (highest first), then by type (instructions first)
        sorted.sort_by(|a, b| {
            let type_order = |t: &ContextType| match t {
                ContextType::Instruction => 0,
                ContextType::Mixed => 1,
                ContextType::Evidence => 2,
            };
            type_order(&a.context_type)
                .cmp(&type_order(&b.context_type))
                .then(b.trust_score.partial_cmp(&a.trust_score).unwrap_or(std::cmp::Ordering::Equal))
        });

        let mut selected = Vec::new();
        let mut total_tokens: u32 = 0;

        for frag in sorted {
            if total_tokens + frag.token_estimate > self.token_budget {
                break;
            }
            total_tokens += frag.token_estimate;
            selected.push(frag.clone());
        }

        AssembledContext {
            fragments: selected,
            total_tokens,
            budget_remaining: self.token_budget.saturating_sub(total_tokens),
        }
    }
}

/// The assembled context, ready for system prompt injection.
#[derive(Debug, Clone)]
pub struct AssembledContext {
    pub fragments: Vec<ContextFragment>,
    pub total_tokens: u32,
    pub budget_remaining: u32,
}

impl AssembledContext {
    /// Render all fragments as a single context string.
    pub fn render(&self) -> String {
        self.fragments.iter()
            .map(|f| f.content.as_str())
            .collect::<Vec<_>>()
            .join("\n\n")
    }

    /// Get fragments by source type.
    pub fn by_source(&self, source_match: &str) -> Vec<&ContextFragment> {
        self.fragments.iter()
            .filter(|f| format!("{:?}", f.source).contains(source_match))
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_fragment(content: &str, trust: f32, tokens: u32, ctx_type: ContextType) -> ContextFragment {
        ContextFragment {
            content: content.into(),
            source: ContextSource::UserStated,
            context_type: ctx_type,
            trust_score: trust,
            token_estimate: tokens,
            created_at: String::new(),
            last_validated: None,
            is_contradicted: false,
        }
    }

    #[test]
    fn test_assemble_within_budget() {
        let mut assembler = ContextAssembler::new(100);
        assembler.add(make_fragment("high trust", 1.0, 30, ContextType::Instruction));
        assembler.add(make_fragment("medium trust", 0.5, 30, ContextType::Evidence));
        assembler.add(make_fragment("low trust", 0.1, 50, ContextType::Evidence));

        let ctx = assembler.assemble();
        assert_eq!(ctx.fragments.len(), 2); // Third doesn't fit
        assert!(ctx.total_tokens <= 100);
        assert_eq!(ctx.fragments[0].content, "high trust"); // Instructions first
    }

    #[test]
    fn test_contradicted_excluded() {
        let mut assembler = ContextAssembler::new(1000);
        assembler.add(make_fragment("valid", 1.0, 10, ContextType::Evidence));
        assembler.add(ContextFragment {
            is_contradicted: true,
            ..make_fragment("stale", 1.0, 10, ContextType::Evidence)
        });

        let ctx = assembler.assemble();
        assert_eq!(ctx.fragments.len(), 1);
        assert_eq!(ctx.fragments[0].content, "valid");
    }

    #[test]
    fn test_instructions_before_evidence() {
        let mut assembler = ContextAssembler::new(1000);
        assembler.add(make_fragment("evidence", 1.0, 10, ContextType::Evidence));
        assembler.add(make_fragment("instruction", 0.5, 10, ContextType::Instruction));

        let ctx = assembler.assemble();
        assert_eq!(ctx.fragments[0].content, "instruction"); // Instructions first despite lower trust
    }

    #[test]
    fn test_render() {
        let mut assembler = ContextAssembler::new(1000);
        assembler.add(make_fragment("part one", 1.0, 10, ContextType::Instruction));
        assembler.add(make_fragment("part two", 0.9, 10, ContextType::Evidence));

        let ctx = assembler.assemble();
        let rendered = ctx.render();
        assert!(rendered.contains("part one"));
        assert!(rendered.contains("part two"));
    }
}
