"""Unit tests for wapt.caddyfile_stamper — Jinja2 render + write."""
from __future__ import annotations

import pytest

from wapt.caddyfile_stamper import CaddyfileStamper
from wapt.config_validation import SiteEntry, utc_now_iso
from wapt.error_library import TemplateError


SITE_TEMPLATE = """\
# Generated by wapt. DO NOT EDIT MANUALLY.
# Source: registry → site "{{ name }}"

{{ domain }} {
\ttls {{ cert_path }} {{ key_path }}
\troot * {{ root }}
\tfile_server browse
\tencode gzip
\tlog {
\t\toutput file {{ log_path }}
\t\tformat json
\t}
}
"""


@pytest.fixture
def stamper(tmp_path):
    templates = tmp_path / "templates"
    templates.mkdir()
    (templates / "site.caddy").write_text(SITE_TEMPLATE, encoding="utf-8")
    return CaddyfileStamper(
        templates_dir=templates,
        sites_enabled_dir=tmp_path / "sites-enabled",
        certs_dir=tmp_path / "certs",
        logs_dir=tmp_path / "logs",
    )


def _entry(name="ecc", domain="ecc.localhost", root="/home/user/ecc"):
    return SiteEntry(
        name=name, domain=domain, root=root, created_at=utc_now_iso()
    )


class TestStamp:
    def test_renders_domain(self, stamper):
        out = stamper.stamp(_entry())
        assert "ecc.localhost {" in out

    def test_includes_root_with_forward_slashes(self, stamper):
        out = stamper.stamp(_entry(root="C:\\Users\\robin\\proj"))
        assert "root * C:/Users/robin/proj" in out

    def test_includes_cert_paths(self, stamper):
        out = stamper.stamp(_entry())
        assert "ecc.localhost.pem" in out
        assert "ecc.localhost-key.pem" in out

    def test_log_path_uses_name(self, stamper):
        out = stamper.stamp(_entry(name="bacowr", domain="bacowr.localhost"))
        assert "bacowr.log" in out

    def test_unknown_template_raises_template_error(self, stamper):
        with pytest.raises(TemplateError):
            stamper.stamp(_entry(), template_name="does-not-exist")


class TestSanitization:
    def test_path_with_newline_rejected(self, stamper):
        with pytest.raises(ValueError):
            stamper.stamp(_entry(root="/home/user\nrm -rf /"))

    def test_path_with_brace_rejected(self, stamper):
        with pytest.raises(ValueError):
            stamper.stamp(_entry(root="/home/user/{evil}"))


class TestFilesystem:
    def test_write_site_caddyfile_creates_file(self, stamper):
        path = stamper.write_site_caddyfile(_entry())
        assert path.exists()
        assert path.name == "ecc.caddy"
        content = path.read_text(encoding="utf-8")
        assert "ecc.localhost {" in content

    def test_write_creates_sites_enabled_dir(self, stamper):
        assert not stamper.sites_enabled_dir.exists()
        stamper.write_site_caddyfile(_entry())
        assert stamper.sites_enabled_dir.exists()

    def test_remove_existing_returns_true(self, stamper):
        stamper.write_site_caddyfile(_entry())
        assert stamper.remove_site_caddyfile("ecc") is True

    def test_remove_missing_returns_false(self, stamper):
        assert stamper.remove_site_caddyfile("never-added") is False

    def test_round_trip_remove_actually_deletes(self, stamper):
        path = stamper.write_site_caddyfile(_entry())
        assert path.exists()
        stamper.remove_site_caddyfile("ecc")
        assert not path.exists()


class TestLineEndings:
    def test_output_is_lf_only(self, stamper):
        path = stamper.write_site_caddyfile(_entry())
        raw = path.read_bytes()
        assert b"\r\n" not in raw, "Caddyfile must use LF, not CRLF"
