#!/usr/bin/env node
/**
 * agent/assembler.mjs
 *
 * WorkspaceBuildR CLI entry point.
 *
 * Usage:
 *   node agent/assembler.mjs "build a production REST API in TypeScript"
 *   node agent/assembler.mjs --offline "build a CLI tool"
 *   node agent/assembler.mjs --test test-cases/rest-api.json
 *   node agent/assembler.mjs --test-all
 */

import { readFile, writeFile, mkdir, readdir } from 'fs/promises';
import { existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { join, dirname } from 'path';

import { deliberate, DEFAULT_CATALOG } from './bdi.mjs';
import { createClient } from './llm.mjs';
import { rankSkills } from './ranker.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Slugify a goal string into a safe directory name.
 *
 * @param {string} goal
 * @returns {string}
 */
function slugify(goal) {
  return goal
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 80);
}

/**
 * Load the skill catalog.
 * Tries data.json at repo root first; falls back to DEFAULT_CATALOG.
 *
 * @returns {Promise<object[]>}
 */
async function loadCatalog() {
  const dataPath = join(REPO_ROOT, 'data.json');
  if (existsSync(dataPath)) {
    try {
      const raw = await readFile(dataPath, 'utf-8');
      const parsed = JSON.parse(raw);
      const catalog = Array.isArray(parsed)
        ? parsed
        : parsed.catalog || parsed.skills || [];
      if (catalog.length > 0) {
        console.log(`[catalog] Loaded ${catalog.length} skills from data.json`);
        return catalog;
      }
    } catch (err) {
      console.warn(`[catalog] Failed to parse data.json (${err.message}), using built-in catalog.`);
    }
  }
  console.log(`[catalog] Using built-in catalog (${DEFAULT_CATALOG.length} skills)`);
  return DEFAULT_CATALOG;
}

// ---------------------------------------------------------------------------
// Output file generators
// ---------------------------------------------------------------------------

/**
 * Generate KICKOFF.md for the output package.
 *
 * @param {string} goal
 * @param {object} bdiTrace
 * @param {object} ranking
 * @returns {string}
 */
function generateKickoffMd(goal, bdiTrace, ranking) {
  const topSkills = ranking.ranked.slice(0, 12);

  const skillBlock = topSkills
    .map(s =>
      `  - slug: ${s.slug}\n    role: ${s.role}\n    reason: >\n      ${s.causalChain.slice(0, 200).replace(/\n/g, ' ')}`
    )
    .join('\n\n');

  const executionSteps = topSkills.map(
    (s, i) => `${i + 1}. **${s.name || s.slug}** (\`${s.slug}\`) — ${s.role}`
  );

  const expectedOutput = bdiTrace.desires
    .map(d => `- ${d.content}`)
    .join('\n');

  return `# Project: ${goal}

## What you're building

${goal}

## Your skills

\`\`\`yaml
skills:
${skillBlock || '  # (no skills selected)'}
\`\`\`

## Execution plan

${executionSteps.join('\n')}

## Expected output

${expectedOutput}

---

*Generated by WorkspaceBuildR — BDI cognitive workspace assembler*
*Model: ${ranking.modelUsed} | Offline: ${ranking.offline}*
`;
}

/**
 * Generate CLAUDE.md for the output package.
 *
 * @param {string} goal
 * @param {object} ranking
 * @returns {string}
 */
function generateClaudeMd(goal, ranking) {
  const core = ranking.ranked.filter(s => s.role === 'core');
  const supporting = ranking.ranked.filter(s => s.role === 'supporting');
  const optional = ranking.ranked.filter(s => s.role === 'optional');

  const fmt = (skills) =>
    skills.length === 0
      ? '  # (none)'
      : skills
          .map(
            s =>
              `  - slug: ${s.slug}\n    reason: >\n      ${s.causalChain.slice(0, 300).replace(/\n/g, ' ')}`
          )
          .join('\n\n');

  const rejectedRows =
    ranking.rejected.length > 0
      ? '\n## Rejected Skills\n\n| Skill | Reason |\n|-------|--------|\n' +
        ranking.rejected
          .map(r => `| \`${r.slug}\` | ${r.reason.slice(0, 130).replace(/\|/g, '/')} |`)
          .join('\n')
      : '';

  return `# Skills for: ${goal}

## Core Skills

\`\`\`yaml
skills:
${fmt(core)}
\`\`\`

## Supporting Skills

\`\`\`yaml
skills:
${fmt(supporting)}
\`\`\`

## Optional Skills

\`\`\`yaml
skills:
${fmt(optional)}
\`\`\`
${rejectedRows}

---

*Generated by WorkspaceBuildR | Model: ${ranking.modelUsed} | Offline: ${ranking.offline}*
`;
}

/**
 * Generate REASONING.md for the output package.
 *
 * @param {string} goal
 * @param {object} bdiTrace
 * @param {object} ranking
 * @returns {string}
 */
function generateReasoningMd(goal, bdiTrace, ranking) {
  const beliefsSection = bdiTrace.beliefs
    .map(
      b =>
        `### ${b.content}\n\n` +
        `**World state:** \`${JSON.stringify(b.worldState).slice(0, 250)}\`\n\n` +
        `**Justified by:** ${b.justification}`
    )
    .join('\n\n');

  const desiresSection = bdiTrace.desires
    .map(d => `- **${d.content}**\n  Motivated by beliefs: ${d.motivatedBy.join(', ')}`)
    .join('\n\n');

  const intentionsSection =
    ranking.ranked.length === 0
      ? '_No skills selected._'
      : ranking.ranked
          .map(
            s =>
              `### \`${s.slug}\` — ${s.role.toUpperCase()} (score: ${s.score}/100)\n\n${s.causalChain}`
          )
          .join('\n\n');

  const rejectedSection =
    ranking.rejected.length === 0
      ? '_No skills rejected._'
      : ranking.rejected.map(r => `- \`${r.slug}\`: ${r.reason}`).join('\n');

  const coreCount = ranking.ranked.filter(s => s.role === 'core').length;
  const totalSelected = ranking.ranked.length;
  const confidence =
    totalSelected > 0 ? Math.round((coreCount / totalSelected) * 100) : 0;

  const offlineNote =
    ranking.offline
      ? '\n> **Note:** Generated in offline mode. Causal chains are token-overlap approximations. Set `GROQ_API_KEY` for full LLM reasoning.\n'
      : '';

  return `# Reasoning Trace

Generated: ${new Date().toISOString()}
Model: ${ranking.modelUsed}
Offline: ${ranking.offline}

---

## Goal

> ${goal}

---

## Beliefs

${beliefsSection}

---

## Desires

${desiresSection}

---

## Intentions (selected)

${intentionsSection}

---

## Rejected skills (with reasons)

${rejectedSection}

---

## Confidence: ${confidence}/100

Confidence is the ratio of core-role skills to total selected skills.
A high ratio indicates strong causal alignment between selected skills and goal requirements.
${offlineNote}`;
}

/**
 * Generate workflows/main.yaml for the output package.
 *
 * @param {string} goal
 * @param {object} bdiTrace
 * @param {object} ranking
 * @returns {string}
 */
function generateWorkflowYaml(goal, bdiTrace, ranking) {
  const steps = ranking.ranked
    .map((s, i) => {
      const safeId = s.slug.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(-40);
      return (
        `  - id: step_${String(i + 1).padStart(2, '0')}_${safeId}\n` +
        `    name: "${(s.name || s.slug).replace(/"/g, "''")}"\n` +
        `    skill: "${s.slug}"\n` +
        `    role: ${s.role}\n` +
        `    score: ${s.score}\n` +
        `    causal_justification: >\n` +
        `      ${s.causalChain.slice(0, 250).replace(/\n/g, ' ')}`
      );
    })
    .join('\n\n');

  const desiredOutcomes = bdiTrace.desires
    .map(d => `  - "${d.content.replace(/"/g, "'")}"`)
    .join('\n');

  return `# WorkspaceBuildR generated workflow
# Goal: ${goal}
# Generated: ${new Date().toISOString()}
# Model: ${ranking.modelUsed}

name: workspace-workflow
goal: "${goal.replace(/"/g, "'")}"

desired_outcomes:
${desiredOutcomes}

steps:
${steps || '  # (no steps — no skills were selected)'}

metadata:
  offline: ${ranking.offline}
  total_skills: ${ranking.ranked.length}
  core_skills: ${ranking.ranked.filter(s => s.role === 'core').length}
  supporting_skills: ${ranking.ranked.filter(s => s.role === 'supporting').length}
  optional_skills: ${ranking.ranked.filter(s => s.role === 'optional').length}
  rejected_skills: ${ranking.rejected.length}
`;
}

// ---------------------------------------------------------------------------
// Core assembler
// ---------------------------------------------------------------------------

/**
 * Run the full assembly pipeline for a goal.
 *
 * @param {string} goal
 * @param {object[]} catalog
 * @param {object} llmClient
 * @returns {Promise<{ outputDir: string, bdiTrace: object, ranking: object }>}
 */
async function assemble(goal, catalog, llmClient) {
  console.log(`\n[assembler] Goal: "${goal}"`);
  console.log(`[assembler] Provider: ${llmClient.provider} | Model: ${llmClient.model}`);

  // Step 1: BDI deliberation (offline, causal, no LLM)
  console.log('[assembler] Running BDI deliberation...');
  const bdiTrace = deliberate(goal, catalog);
  console.log(
    `[assembler] Beliefs: ${bdiTrace.beliefs.length} | ` +
    `Desires: ${bdiTrace.desires.length} | ` +
    `Pre-selected: ${bdiTrace.intentions.selected.length} | ` +
    `Pre-rejected: ${bdiTrace.intentions.rejected.length}`
  );

  // Step 2: LLM ranking (or offline fallback)
  console.log('[assembler] Ranking skills with causal analysis...');
  const ranking = await rankSkills(goal, catalog, llmClient);
  console.log(
    `[assembler] Ranked: ${ranking.ranked.length} | ` +
    `Rejected: ${ranking.rejected.length} | ` +
    `Offline: ${ranking.offline}`
  );

  // Step 3: Write output package
  const slug = slugify(goal);
  const outputDir = join(REPO_ROOT, 'outputs', slug);
  const workflowDir = join(outputDir, 'workflows');

  await mkdir(workflowDir, { recursive: true });

  await writeFile(join(outputDir, 'KICKOFF.md'), generateKickoffMd(goal, bdiTrace, ranking), 'utf-8');
  await writeFile(join(outputDir, 'CLAUDE.md'), generateClaudeMd(goal, ranking), 'utf-8');
  await writeFile(join(outputDir, 'REASONING.md'), generateReasoningMd(goal, bdiTrace, ranking), 'utf-8');
  await writeFile(join(workflowDir, 'main.yaml'), generateWorkflowYaml(goal, bdiTrace, ranking), 'utf-8');

  console.log(`[assembler] Package written: ${outputDir}`);
  return { outputDir, bdiTrace, ranking };
}

// ---------------------------------------------------------------------------
// Test runner
// ---------------------------------------------------------------------------

/**
 * Score a single test case JSON file.
 *
 * Scoring breakdown:
 *   40 pts — expected skills present in selected list
 *   40 pts — causal expectations matched in causal chains
 *   20 pts — not-expected skills correctly rejected
 *
 * @param {string} testCasePath
 * @param {object[]} catalog
 * @param {object} llmClient
 * @returns {Promise<{ file: string, goal: string, score: number, details: string[] }>}
 */
async function runTestCase(testCasePath, catalog, llmClient) {
  const raw = await readFile(testCasePath, 'utf-8');
  const tc = JSON.parse(raw);
  const {
    goal,
    expectedSkills = [],
    causalExpectations = [],
    notExpected = [],
  } = tc;

  const { ranking } = await assemble(goal, catalog, llmClient);
  const selectedSlugs = new Set(ranking.ranked.map(s => s.slug));
  const rejectedSlugs = new Set(ranking.rejected.map(s => s.slug));

  const details = [];
  let points = 0;
  let maxPoints = 0;

  // --- Part 1: Expected skills present (40 pts) ---
  if (expectedSkills.length > 0) {
    const pts = 40 / expectedSkills.length;
    for (const slug of expectedSkills) {
      maxPoints += pts;
      if (selectedSlugs.has(slug)) {
        points += pts;
      } else {
        details.push(`MISS: "${slug}" expected in selected but absent`);
      }
    }
  }

  // --- Part 2: Causal chain quality (40 pts) ---
  if (causalExpectations.length > 0) {
    const pts = 40 / causalExpectations.length;
    for (const exp of causalExpectations) {
      maxPoints += pts;
      const ranked = ranking.ranked.find(s => s.slug === exp.skill);
      if (!ranked) {
        details.push(`MISS: causal expectation for "${exp.skill}" but skill not selected`);
        continue;
      }
      const expectedWords = exp.causation
        .toLowerCase()
        .split(/\W+/)
        .filter(w => w.length > 4);
      const chainLower = (ranked.causalChain || '').toLowerCase();
      const matched = expectedWords.filter(w => chainLower.includes(w)).length;
      const ratio = expectedWords.length > 0 ? matched / expectedWords.length : 0;
      if (ratio >= 0.4) {
        points += pts;
      } else {
        details.push(
          `WEAK CAUSATION: "${exp.skill}" chain matched ${Math.round(ratio * 100)}% of expected terms`
        );
      }
    }
  }

  // --- Part 3: Not-expected correctly rejected (20 pts) ---
  if (notExpected.length > 0) {
    const pts = 20 / notExpected.length;
    for (const slug of notExpected) {
      maxPoints += pts;
      if (rejectedSlugs.has(slug)) {
        points += pts;
      } else if (selectedSlugs.has(slug)) {
        details.push(`FALSE POSITIVE: "${slug}" should be rejected but was selected`);
      } else {
        // Not addressed at all — partial credit
        points += pts * 0.5;
        details.push(`OMISSION: "${slug}" should be explicitly rejected but not mentioned`);
      }
    }
  }

  const score = maxPoints > 0 ? Math.round((points / maxPoints) * 100) : 0;
  return { file: testCasePath, goal, score, details };
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

async function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('--help')) {
    console.log('WorkspaceBuildR — BDI Workspace Assembler\n');
    console.log('Usage:');
    console.log('  node agent/assembler.mjs "your goal here"');
    console.log('  node agent/assembler.mjs --offline "your goal"');
    console.log('  node agent/assembler.mjs --test test-cases/rest-api.json');
    console.log('  node agent/assembler.mjs --test-all');
    console.log('\nEnvironment:');
    console.log('  GROQ_API_KEY   Groq API key (free at console.groq.com)');
    console.log('                 Omit to run in offline mode automatically');
    process.exit(0);
  }

  const isOffline = args.includes('--offline');
  const isTest = args.includes('--test');
  const isTestAll = args.includes('--test-all');

  const catalog = await loadCatalog();
  const llmClient = createClient(isOffline ? { provider: 'offline' } : {});

  // --test-all
  if (isTestAll) {
    const testDir = join(REPO_ROOT, 'test-cases');
    let testFiles = [];
    try {
      const entries = await readdir(testDir);
      testFiles = entries.filter(f => f.endsWith('.json')).map(f => join(testDir, f));
    } catch {
      console.error('[test-all] Cannot read test-cases/ directory.');
      process.exit(1);
    }

    if (testFiles.length === 0) {
      console.log('[test-all] No .json files found in test-cases/');
      process.exit(0);
    }

    console.log(`\n[test-all] Running ${testFiles.length} test cases...\n`);
    const results = [];

    for (const tf of testFiles) {
      try {
        const result = await runTestCase(tf, catalog, llmClient);
        results.push(result);
      } catch (err) {
        results.push({
          file: tf,
          goal: '(error)',
          score: 0,
          details: [`ERROR: ${err.message}`],
        });
      }
    }

    const W = 32;
    console.log('\n' + '='.repeat(72));
    console.log('TEST RESULTS — WorkspaceBuildR');
    console.log('='.repeat(72));
    console.log(`${'Test case'.padEnd(W)} ${'Score'.padStart(6)}  Bar`);
    console.log('-'.repeat(72));
    for (const r of results) {
      const name = r.file.split(/[/\\]/).pop().replace('.json', '');
      const bar = '█'.repeat(Math.round(r.score / 10)) + '░'.repeat(10 - Math.round(r.score / 10));
      console.log(`${name.padEnd(W)} ${String(r.score).padStart(5)}%  ${bar}`);
      for (const d of r.details) {
        console.log(`  ${d}`);
      }
    }
    console.log('='.repeat(72));
    const avg = Math.round(results.reduce((s, r) => s + r.score, 0) / results.length);
    console.log(`Average: ${avg}/100`);
    console.log('='.repeat(72) + '\n');
    return;
  }

  // --test <file>
  if (isTest) {
    const testFileArg = args.find(a => !a.startsWith('--'));
    if (!testFileArg) {
      console.error('[test] Usage: node agent/assembler.mjs --test test-cases/rest-api.json');
      process.exit(1);
    }
    const testPath =
      testFileArg.startsWith('/') || /^[A-Za-z]:/.test(testFileArg)
        ? testFileArg
        : join(process.cwd(), testFileArg);

    try {
      const result = await runTestCase(testPath, catalog, llmClient);
      console.log('\n' + '='.repeat(60));
      console.log(`TEST: ${result.file.split(/[/\\]/).pop()}`);
      console.log(`Goal: ${result.goal}`);
      console.log(`Score: ${result.score}/100`);
      if (result.details.length > 0) {
        console.log('\nDivergences:');
        for (const d of result.details) console.log(`  - ${d}`);
      } else {
        console.log('All expectations met — no divergences.');
      }
      console.log('='.repeat(60) + '\n');
    } catch (err) {
      console.error(`[test] Failed: ${err.message}`);
      if (process.env.DEBUG) console.error(err.stack);
      process.exit(1);
    }
    return;
  }

  // Normal assembly run
  const goal = args.filter(a => !a.startsWith('--')).join(' ').trim();
  if (!goal) {
    console.error('[assembler] No goal provided. Run with --help for usage.');
    process.exit(1);
  }

  try {
    const { outputDir, ranking } = await assemble(goal, catalog, llmClient);

    const coreCount = ranking.ranked.filter(s => s.role === 'core').length;
    const supportCount = ranking.ranked.filter(s => s.role === 'supporting').length;
    const optCount = ranking.ranked.filter(s => s.role === 'optional').length;

    console.log('\n' + '='.repeat(60));
    console.log('ASSEMBLY COMPLETE');
    console.log('='.repeat(60));
    console.log(`Goal:    ${goal}`);
    console.log(`Output:  ${outputDir}`);
    console.log(`Skills:  ${ranking.ranked.length} selected (${coreCount} core, ${supportCount} supporting, ${optCount} optional)`);
    console.log(`         ${ranking.rejected.length} rejected with documented reasons`);
    console.log(`Model:   ${ranking.modelUsed}`);
    console.log('='.repeat(60));
    console.log('\nPackage files:');
    console.log(`  ${outputDir}/KICKOFF.md`);
    console.log(`  ${outputDir}/CLAUDE.md`);
    console.log(`  ${outputDir}/REASONING.md`);
    console.log(`  ${outputDir}/workflows/main.yaml`);
    console.log('');
  } catch (err) {
    console.error(`[assembler] Fatal error: ${err.message}`);
    if (process.env.DEBUG) console.error(err.stack);
    process.exit(1);
  }
}

main();
